apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  namespace: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: balaakashreddyy/student-management-portal:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo-root:securepass@mongo-service:27017/studentdb?authSource=admin
