apiVersion: v1
kind: Service
metadata:
  name: student-app-service
  namespace: student-app
spec:
  type: LoadBalancer
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
