apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: balaakashreddyy/student-management:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://root:securepass@mongo-service:27017/studentdb?authSource=admin"